<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ClientInvoice;
use App\Models\InvoiceItem;
use App\Models\InvoiceLog;
use App\Models\PaymentReceipt;
use App\Models\Order;
use App\Models\User;
use Carbon\Carbon;

class InvoiceSeeder extends Seeder
{
    public function run(): void
    {
        $clients = User::where('user_role', 2)->get();

        if ($clients->isEmpty()) {
            $this->command->error('No clients found. Please run ClientSeeder first.');
            return;
        }

        $statuses = [
            ClientInvoice::STATUS_GENERATED,
            ClientInvoice::STATUS_CONFIRMED,
            ClientInvoice::STATUS_PAID
        ];

        for ($monthsBack = 5; $monthsBack >= 0; $monthsBack--) {
            $invoiceDate = Carbon::now()->subMonths($monthsBack)->startOfMonth();
            $dueDate = $invoiceDate->copy()->addDays(30);

            foreach ($clients as $client) {
               
                $existingInvoice = ClientInvoice::where('client_id', $client->id)
                    ->whereYear('invoice_date', $invoiceDate->year)
                    ->whereMonth('invoice_date', $invoiceDate->month)
                    ->first();

                if ($existingInvoice) {
                    $this->command->info("Invoice already exists for {$client->full_name} in {$invoiceDate->format('F Y')}");
                    continue;
                }

             
                if (rand(1, 100) <= 80) { 
                    $this->createInvoiceForClient($client, $invoiceDate, $dueDate, $statuses);
                }
            }
        }
    }

    private function createInvoiceForClient($client, $invoiceDate, $dueDate, $statuses)
    {
       
        $orderCount = rand(50, 300);
        $orders = collect();
        
        for ($i = 0; $i < $orderCount; $i++) {
            $orders->push((object)[
                'id' => rand(10000, 99999),
                'service_fees' => rand(5, 25), 
                'created_at' => $invoiceDate->copy()->addDays(rand(0, 27))
            ]);
        }

        $subtotal = $orders->sum('service_fees');
        $taxRate = 0.15; 
        $taxAmount = $subtotal * $taxRate;
        $totalAmount = $subtotal + $taxAmount;

        // Generate unique invoice number
        $invoiceNumber = $this->generateUniqueInvoiceNumber($invoiceDate, $client->id);

        try {
            $invoice = ClientInvoice::create([
                'client_id' => $client->id,
                'invoice_number' => $invoiceNumber,
                'invoice_date' => $invoiceDate,
                'due_date' => $dueDate,
                'status' => $statuses[array_rand($statuses)],
                'subtotal' => $subtotal,
                'tax_amount' => $taxAmount,
                'total_amount' => $totalAmount,
                'currency' => 'SAR',
                'client_emails' => $client->client?->billing_emails ?? [$client->email],
                'notes' => $client->client?->invoice_template_notes,
                'payment_token' => \Str::random(32),
                'zatca_qr_code' => null, 
            ]);

            InvoiceItem::create([
                'invoice_id' => $invoice->id,
                'description' => "Delivery services for " . $invoiceDate->format('F Y') . " ({$orderCount} orders)",
                'quantity' => $orderCount,
                'unit_price' => $orderCount > 0 ? $subtotal / $orderCount : 0,
                'total_price' => $subtotal,
                'service_month' => $invoiceDate->format('Y-m-01')
            ]);

            InvoiceLog::create([
                'invoice_id' => $invoice->id,
                'action' => 'created',
                'user_id' => 1, 
                'old_data' => null,
                'new_data' => $invoice->toArray(),
                'notes' => 'Invoice automatically generated by seeder for ' . $invoiceDate->format('F Y')
            ]);

            if ($invoice->status !== ClientInvoice::STATUS_GENERATED) {
                InvoiceLog::create([
                    'invoice_id' => $invoice->id,
                    'action' => 'confirmed',
                    'user_id' => 1,
                    'old_data' => ['status' => ClientInvoice::STATUS_GENERATED],
                    'new_data' => ['status' => $invoice->status],
                    'notes' => 'Invoice confirmed by system admin'
                ]);
            }

            if ($invoice->status === ClientInvoice::STATUS_PAID) {
                $this->createPaymentForInvoice($invoice, $dueDate, $totalAmount);
            }

            $this->command->info("Created invoice {$invoice->invoice_number} for {$client->full_name}");

        } catch (\Exception $e) {
            $this->command->error("Failed to create invoice for {$client->full_name}: " . $e->getMessage());
        }
    }

    private function generateUniqueInvoiceNumber($invoiceDate, $clientId)
    {
        $yearMonth = $invoiceDate->format('Ym');
        $attempt = 1;
        
        do {
          
            $suffix = str_pad($clientId, 2, '0', STR_PAD_LEFT) . str_pad($attempt, 2, '0', STR_PAD_LEFT);
            $invoiceNumber = "INV-{$yearMonth}-{$suffix}";
            
            $exists = ClientInvoice::where('invoice_number', $invoiceNumber)->exists();
            
            if ($exists) {
                $attempt++;
            }
        } while ($exists && $attempt <= 99);

        if ($attempt > 99) {
           
            $invoiceNumber = "INV-{$yearMonth}-" . time() . rand(10, 99);
        }
        
        return $invoiceNumber;
    }

    private function createPaymentForInvoice($invoice, $dueDate, $totalAmount)
    {
        $paymentMethods = ['bank_transfer', 'cash', 'tap_gateway'];
        $paymentMethod = $paymentMethods[array_rand($paymentMethods)];
        
        $receipt = PaymentReceipt::create([
            'invoice_id' => $invoice->id,
            'amount_paid' => $totalAmount,
            'payment_date' => $dueDate->copy()->subDays(rand(1, 15)), // Paid before due date
            'payment_method' => $paymentMethod,
            'transaction_reference' => 'TXN-' . \Str::upper(\Str::random(8)),
            'status' => PaymentReceipt::STATUS_CONFIRMED,
            'notes' => 'Payment received and confirmed',
            'payment_details' => [
                'method' => $paymentMethod,
                'recorded_by' => 'System Seeder',
                'recorded_at' => now()
            ]
        ]);

        InvoiceLog::create([
            'invoice_id' => $invoice->id,
            'action' => 'payment_recorded',
            'user_id' => 1,
            'old_data' => null,
            'new_data' => $receipt->toArray(),
            'notes' => 'Payment recorded via ' . $paymentMethod
        ]);

        InvoiceLog::create([
            'invoice_id' => $invoice->id,
            'action' => 'marked_paid',
            'user_id' => 1,
            'old_data' => ['status' => ClientInvoice::STATUS_CONFIRMED],
            'new_data' => ['status' => ClientInvoice::STATUS_PAID],
            'notes' => 'Invoice marked as paid after payment confirmation'
        ]);
    }
}
